version: '3.7'

services:
  postgres:
    image: 'postgres'
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'